#!/usr/bin/env bash

source "vars"
source "functions"

# Global options
QUIET=0
DEFAULT=1

# Get options
short_options="c:i::hl:m:svx"
long_options="config=:,cc:,info::,help,label=:,mounts:,silent,version,"
options=$(getopt -o $short_options -l $long_options -n "$SRCBUILD" -- "$@")
return=$?

# Unable to get options
if [ $return -ne 0 ]
then
		_EX=$EXIT_CANTCREATE; _die "getopt return - ${return}"
fi

# No options supplied
if [ -z $1 ]
then
		_usage_error
fi

# Execution
eval set -- "$options"
unset options

while :
do
		case "$1" 
		in
				'-c'|'--config=') MAKESRC_USER_CONFIG="$2"; shift 2; continue ;;
				'-s'|'--silent') QUIET=1; shift 2; continue ;;
				'-i'|'--info') case "$2"
							   in
									   '-a'|'--all') : ;; #cmd_get_info_long
										*) cmd_get_info ;;
							   esac
							   shift 2; break ;;
				'--cc') case "$2" in 
							 	'-l'| --label=) : ;; #
								*) : ;;	# arguments required
					 	esac
						shift; continue ;;
				'-h'|'--help') _usage; break ;;
				'-v'|'--version') _version; break ;;
				'--') shift; break ;;
				*) _usage_error; break ;;
		esac
done

if [ "$SRCBUILD" == "SRCBUILD" ];
then
		_cmd_makesrc
fi

exit $?

