#!/usr/bin/env bash

srcname=binutils
srcver=2.30

srcinfo='Binutils includes tools capable of creating and managing binary program files, including handling object files, libraries, profile data, and assembly source code.'
srccpy=('GPLv2' 'GPLv3' 'LGPLv2')
srcurl=(https://www.gnu.org/software/binutils/)
srcget=(https://ftp.gnu.org/gnu/$srcname/${srcname}-${srcver}.tar.gz)
srcsig=(${srcget}.sig)

#depends=('bash' 'binutils' 'coreutils' 'diffutils' 'file' 'gawk' 'gcc' 'glibc' 'grep' 'make' 'perl' 'sed' 'texinfo' 'zlib')
depends_test=('dejagnu' 'expect')
provides=('ld' 'as' 'addr2line' 'ar' 'c++filt' 'dlltool' 'gold' 'gprof' 'nlmconv' 'nm' 'objcopy' 'objdump' 'ranlib' 'readelf' 'size' 'strings' 'strip' 'windmc' 'windres')
conflicts=('')

ccsrcbuild_pass_1(){
		
		#cd $SOURCE_DIR/$srcname
		#tar -xzvf ${srcname}-${srcver}.tar.gz
		#mv -v ${srcname}-${srcver} $srcver
		#
		mkdir -v $srcver/build
		cd $srcver/build
		../configure --prefix=/$CCTC_USR			\
		   			 --with-sysroot=$TGTBUILD_DIR	\
					 --with-lib-path=/$CCTC_USR/lib	\
		   			 --target=$TGTBUILD_TGT			\
		   			 --disable-nls					\
		   			 --disable-werror
		make
		case $(uname -m) in
				x86_64) mkdir -v /$CCTC_USR/lib && ln -sv lib /$CCTC_USR/lib64 ;;
		esac
		make install
		cd ~ && rm -rfv ${srcname}/${srcver}
}

